### ISSUE TITLE
error  running file example.py

### ISSUE THREAD

**Issue by mangeshsable1975** [TechfaneTechnologies/QtsApp#2]
[Running] python -u "g:\QNTSAPP\QtsApp\example.py"
Traceback (most recent call last):
  File "g:\QNTSAPP\QtsApp\example.py", line 2, in <module>
    from qtsapp import *
  File "g:\QNTSAPP\QtsApp\qtsapp\__init__.py", line 24, in <module>
    from qtsapp.QtsApp import *
  File "g:\QNTSAPP\QtsApp\qtsapp\QtsApp.py", line 19, in <module>
    from dotenv import dotenv_values
ModuleNotFoundError: No module named 'dotenv'

[Done] exited with code=1 in 26.723 seconds

**Comment by MooneDrJune** [comment]
> [Running] python -u "g:\QNTSAPP\QtsApp\example.py" Traceback (most recent call last): File "g:\QNTSAPP\QtsApp\example.py", line 2, in from qtsapp import * File "g:\QNTSAPP\QtsApp\qtsapp__init__.py", line 24, in from qtsapp.QtsApp import * File "g:\QNTSAPP\QtsApp\qtsapp\QtsApp.py", line 19, in from dotenv import dotenv_values ModuleNotFoundError: No module named 'dotenv'
> 
> [Done] exited with code=1 in 26.723 seconds

Please run the following `pip install python-dotenv`

**Comment by mangeshsable1975** [comment]
i have installed pip with cmd (pip install python-dotenv) and run the command
new error

[Running] python -u "g:\QNTSAPP\QtsApp\example.py"
:0: UserWarning: You do not have a working installation of the service_identity module: 'No module named 'service_identity''.  Please install it from <https://pypi.python.org/pypi/service_identity> and make sure all of its dependencies are satisfied.  Without the service_identity module, Twisted can perform only rudimentary TLS client hostname verification.  Many valid certificate/hostname mappings may be rejected.

**Comment by MooneDrJune** [comment]
> 'No module named 'service_identity''. Please install it from https://pypi.python.org/pypi/service_identity and make sure all of its dependencies are satisfied.

`pip install service-identity`
