### ISSUE TITLE
Connection is connected but its not getting updated in Excel

### ISSUE THREAD

**Issue by AkilGoku** [TechfaneTechnologies/QtsApp#6]
<img width="1279" alt="image" src="https://user-images.githubusercontent.com/11856463/184847587-fd48aa99-1c04-4add-989d-a4d219821854.png">

Have attached the image for your reference.

**Comment by MooneDrJune** [comment]
> It was due to not completing the registration using mobile number in QtsApp site. Now it seems to work. Thanks :)

If its not working just upgrade the lib once again. In addition the library MSV Python is 3.10
